[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_25_keypair_vs_pda = "GQAa8VBnLDX2ArwaSaYFeNt66ydoU3qxpPbgmDr6Ef6f"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/franck/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
