[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_30_close_program = "E9hD5YJbEjaP2LGG9KRwXUdRvfYGc6LKxdM9goFDmhtd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/franck/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
