[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_14 = "BWBtaUY6gZBZKEYvPF1vgnU5vM7DuCxCduAHnEUSuiqs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/franck/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
