[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
read_write_storage = "6AHTMuew9aNk4RWEaYNJ18mBEeVrrDaiwwpcGgLqui3o"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/franck/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
