[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_27_init_if_needed = "8QKTaZTQ1wKYR84zidELzC5qbpA94wQXaTnBgPrx9Yfw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/franck/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
