[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_23_sol_splitter = "G2kt7QBk3Xp7x6h14JpnJn66iQE1oaZyjd9VSC8j7JPZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/franck/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
