[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
alice = "FLuUHoSt8DqMW4JVnWRjSbz6JtZq6xxqMc6A3PWehP6q"
bob = "FNvGvvH3eHRUBRnSNxyrBjQsxnDipCdFox9NtQMm2sTi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/franck/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
