[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_29_owner_authority = "EWLtK97QB7ipGWrUynMJE4J4Q6jf486MsA9yVtFg6MEY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/franck/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
