[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_02 = "6Q3jZR97LHruhME6ZLG2fyyxPf64hS2jcnZr5eCvt8iB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/franck/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
