[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_19_example_map = "x5MkyBjzr9UynGFks6HmSQgWD4qAcsdmff8JTvgHyv5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/franck/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
