[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
deploy_tutorial = "CDYnRYE3tbKwihoQ6MEqEU4oxsQERZg6eSBHcH1neWNU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/franck/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
